### PR TITLE
Tweaked out Agricraft

### PR DESCRIPTION
**Pull request by frenchiveruti**
As the mod isn't in game, the agricraft lines were giving out errors, removed them to avoid that.

### CODE REVIEW

**Comment by frenchiveruti** [comment]
Closed until I finish.

**Comment by frenchiveruti** [comment]
Finished, directly related to #576 
This fixes that.

**Comment by scalda** [comment]
I don't understand this as agricraft is in the pack?

**Comment by frenchiveruti** [comment]
It is not, I swear:
https://github.com/scalda/FoolCraft/tree/master/mods

**Comment by frenchiveruti** [comment]
Ok, second comment as I don't want to keep editing the previous one.
Agricraft dev deletes older jar files from curse, so the CMPDL can't download the versions stated here https://github.com/scalda/FoolCraft/tree/master/mods  (in this case Agricraft a15)
Is there a way to know if the people with the Curse Launcher have the same issue?
Because it is a big deal as it just breaks any tweak that you make .

**Comment by scalda** [comment]
Well i just pulled a clean install of the pack from curse and it grabbed agricraft no problem

**Comment by frenchiveruti** [comment]
Ah... Then is CMPDL the issue here, gladly you have the mod list here on the Git so I can grab the missing mods.  
Sorry for the weird pull request, you can close it anytime :+1:

**Pull request closed without merging**
